package com.hzy.pojo;

import java.io.Serializable;


public class Project implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public Project(){
		
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String project_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.student_id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String snumber;
    private String student_name;
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_category
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String project_category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.createtime
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.result
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.funds
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String funds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.team
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.introduction
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.research_contents
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String research_contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.plan
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String plan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String status;
    private String t_Name;
    private String evaluat;
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getProject_name() {
		return project_name;
	}
	public void setProject_name(String project_name) {
		this.project_name = project_name;
	}
	public String getSnumber() {
		return snumber;
	}
	public void setSnumber(String snumber) {
		this.snumber = snumber;
	}
	public String getStudent_name() {
		return student_name;
	}
	public void setStudent_name(String student_name) {
		this.student_name = student_name;
	}
	public String getCollege() {
		return college;
	}
	public void setCollege(String college) {
		this.college = college;
	}

	public String getProject_category() {
		return project_category;
	}
	public void setProject_category(String project_category) {
		this.project_category = project_category;
	}
	public String getCreatetime() {
		return createtime;
	}
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}
	public String getResult() {
		return result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public String getFunds() {
		return funds;
	}
	public void setFunds(String funds) {
		this.funds = funds;
	}
	public String getTeam() {
		return team;
	}
	public void setTeam(String team) {
		this.team = team;
	}
	public String getIntroduction() {
		return introduction;
	}
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}
	public String getResearch_contents() {
		return research_contents;
	}
	public void setResearch_contents(String research_contents) {
		this.research_contents = research_contents;
	}
	public String getPlan() {
		return plan;
	}
	public void setPlan(String plan) {
		this.plan = plan;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getT_Name() {
		return t_Name;
	}
	public void setT_Name(String t_Name) {
		this.t_Name = t_Name;
	}
	public Project(String project_name, String snumber, String student_name,
			String college, String project_category, String createtime,
			String result, String funds, String team, String introduction,
			String research_contents, String plan, String status, String t_Name) {
		super();
		this.project_name = project_name;
		this.snumber = snumber;
		this.student_name = student_name;
		this.college = college;
		this.project_category = project_category;
		this.createtime = createtime;
		this.result = result;
		this.funds = funds;
		this.team = team;
		this.introduction = introduction;
		this.research_contents = research_contents;
		this.plan = plan;
		this.status = status;
		this.t_Name = t_Name;
	}
	public String getEvaluat() {
		return evaluat;
	}
	public void setEvaluat(String evaluat) {
		this.evaluat = evaluat;
	}
}